name = "interviewkit"
compatibility_date = "2024-01-15"

[env.production]
name = "interviewkit"

[build]
command = "npm install && npm run build:cf"
cwd = "."
watch_dir = "src"

[build.environment]
NODE_VERSION = "18.18.0"
NPM_VERSION = "8.19.0"

[[env.production.routes]]
pattern = "interview-kit-cf.pages.dev/*"
zone_name = "" 